#pragma once

#include <algorithm>
#include <deque>
#include <iostream>
#include <fstream>
#include <functional>
#include <list>
#include <memory>
#include <numeric>
#include <regex>
#include <string>
#include <sstream>
#include <set>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
